### ISSUE TITLE
[RELEASE ISSUE] Checklist for first official release of cif_mag.dic

### ISSUE THREAD

**Issue by jamesrhester** [COMCIFS/magnetic_dic#61]
In concert with the next edition of Volume G I suggest we release v1.0.0 of cif_mag.dic. See [here](https://github.com/COMCIFS/cif_core/issues/317#issue-1521881017) for an example of how this is done.

- [ ] Release manager appointed
- [ ] `_dictionary_audit.revision` comments summarised
- [ ] Release branch created
- [ ] Next version placeholder created in dictionary_audit section in main branch
- [ ] Plain text summary of changes created
- [ ] COMCIFS advised of any COMCIFS-significant updates (e.g. changes in units)
- [ ] Magnetic Structures Commission advised
- [ ] All comments during review period addressed (add to list below)
- [ ] Final DOI and URL edited into file (IUCr Chester office to advise of DOI)
- [ ] Github release tagged
- [ ] IUCr updated with released file

Outstanding pull requests/issues that should be resolved before releasing. Only easy or janitorial to go here. Please check any of your pet PRs or issues and add to the list below.
#60

**Comment by vaitkus** [comment]
I added a few more per PRs of mine to the list, but almost all of them seem quite straightforward and easy to merge. Please remove if any of them seem irrelevant.

**Comment by jamesrhester** [comment]
Removed #59 as the magnetic CIF portion of this has been resolved.

**Comment by jamesrhester** [comment]
I will appoint myself release manager. If someone else would like to do it feel free to take over.

**Comment by rowlesmr** [comment]
Found some things to fix, which I'll put in a separate issue around `_structure.id`.

**Comment by jamesrhester** [comment]
I've updated the release tickboxes. After the latest PRs #103, #104 are merged we just need an author list and we're ready to create a release candidate, I think.
